### ISSUE TITLE
Generating audio after model training

### ISSUE THREAD

**Issue by Himanshu-KF** [ebadawy/voice_conversion#1]
How to generate or convert is not mentioned in the README after model training is done. Can you please add that to readme as well?

Great work on this! I saw the results and they look promising.

**Comment by ebadawy** [comment]
Thanks for the suggestion. We are working on that and it should be added soon.

**Comment by RussellSB** [comment]
Hi @Himanshu-KF just to let you know a inference.py has been added for this! It accepts an input wav, and saves a wav in the style of the target speaker. The saved wav is a reconstruction from Griffin Lim, then you can pass the wav to vocoders like WaveNet or MelGAN to improve its quality.
