### ISSUE TITLE
The output vocals have serious electronic sounds

### ISSUE THREAD

**Issue by FashengChen0622** [ebadawy/voice_conversion#10]
Hello, I used the pretrained model you provided to infer the audio provided in your github.io webpage.
The result obtained has a very heavy electronic sound (the output result is pretty bad compared with your demo on your github.io webpage)
Can you provide the pretrained model, method and parameters , which correspond to the github.io webpage demo?
I will be very grateful.

**Comment by RussellSB** [comment]
Yes, the reason why it doesn't sound as high quality is that it is the Griffin Lim reconstruction. The Griffin Lim reconstruction audio must then be fed to a vocoder such as WaveNet to reconstruct at a higher quality as showcased in the demo. This way, spectrogram parameters of this VAE-GAN aren't forced to match that of the vocoder making it adaptable to a lot of audio generation vocoders.

I recommend using a vocoder like:
- WaveNet (https://github.com/r9y9/wavenet_vocoder)     <----- what was used for the paper
- MelGAN (https://github.com/descriptinc/melgan-neurips)      <---- easier to train/setup

Amongst other options for better speed (https://www.reddit.com/r/MachineLearning/comments/ivj9l0/d_which_vocoder_is_the_best_for_speech_synthesis/).

The paper trained a WaveNet vocoder on both speakers at once, which makes training considerably faster. Training a Wavenet vocoder per speaker is another approach, though it takes longer it makes things adaptable for extending to many-to-many style transfer. Also, some argue that per speaker allows it to vocode at a high higher quality.

I'm working on a [repo](https://github.com/RussellSB/tt-vae-gan) on how to use this VAE-GAN codebase with the WaveNet vocoder codebase and considering uploading my pre-trained models of WaveNet to there soon. As I'm typing this, the README.md still needs to be readded, but I'm working on that now - a tutorial should be up soon.
