### ISSUE TITLE
Getting Error During Training

### ISSUE THREAD

**Issue by flancast90** [ebadawy/voice_conversion#26]
Hi,
I've been working with this model for a week or so now, and am running into an error when I try to train the model. Everything seems to be in place and ready for training - all of the pickle files are prepared and contain data, for instance. I'd be happy to get any help or guidance on what I can do to fix this. Thanks!

Here's the full error message:
```py
  File "D:\model\speech\train.py", line 300, in train
    for i, batch in progress:
  File "C:\Users\Finn Lancaster\AppData\Local\Programs\Python\Python310\lib\site-packages\tqdm\std.py", line 1195, in __iter__
    for obj in iterable:
  File "C:\Users\Finn Lancaster\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\data\dataloader.py", line 634, in __next__
    data = self._next_data()
  File "C:\Users\Finn Lancaster\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\data\dataloader.py", line 1346, in _next_data
    return self._process_data(data)
  File "C:\Users\Finn Lancaster\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\data\dataloader.py", line 1372, in _process_data
    data.reraise()
  File "C:\Users\Finn Lancaster\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\_utils.py", line 644, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "C:\Users\Finn Lancaster\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\data\_utils\worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "C:\Users\Finn Lancaster\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\data\_utils\fetch.py", line 54, in fetch
    return self.collate_fn(data)
  File "C:\Users\Finn Lancaster\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\data\_utils\collate.py", line 264, in default_collate
    return collate(batch, collate_fn_map=default_collate_fn_map)
  File "C:\Users\Finn Lancaster\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\data\_utils\collate.py", line 127, in collate
    return elem_type({key: collate([d[key] for d in batch], collate_fn_map=collate_fn_map) for key in elem})
  File "C:\Users\Finn Lancaster\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\data\_utils\collate.py", line 127, in <dictcomp>
    return elem_type({key: collate([d[key] for d in batch], collate_fn_map=collate_fn_map) for key in elem})
  File "C:\Users\Finn Lancaster\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\data\_utils\collate.py", line 119, in collate
    return collate_fn_map[elem_type](batch, collate_fn_map=collate_fn_map)
  File "C:\Users\Finn Lancaster\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\data\_utils\collate.py", line 171, in collate_numpy_array_fn
    return collate([torch.as_tensor(b) for b in batch], collate_fn_map=collate_fn_map)
  File "C:\Users\Finn Lancaster\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\data\_utils\collate.py", line 171, in <listcomp>
    return collate([torch.as_tensor(b) for b in batch], collate_fn_map=collate_fn_map)
RuntimeError: Could not infer dtype of numpy.float32
```

**Comment by magicse** [comment]
> ```python
>   File "D:\model\speech\train.py", line 300, in train
>     for i, batch in progress:
> ```
I saw line 300  but file https://github.com/ebadawy/voice_conversion/blob/master/src/train.py consist 280 strings only.

**Comment by flancast90** [comment]
> > ```python
> >   File "D:\model\speech\train.py", line 300, in train
> >     for i, batch in progress:
> > ```
> 
> I saw line 300 but file https://github.com/ebadawy/voice_conversion/blob/master/src/train.py consist 280 strings only.

I had run a linter on the code to make it more readable. Just to be sure that that wasn't causing it, I copied the code directly from the main branch and ran that, and got the same error again. It seems to be an issue with the DataLoader, possibly related to unpickling the data, I have an extremely large dataset of wav files I'm training on. The pickle file for training was nearly 2 GB in size, so I'm not sure if that could have caused it... You're more familiar with the code than I, so maybe I'm missing something simple.

**Comment by magicse** [comment]
> You're more familiar with the code than I, so maybe I'm missing something simple.

I just downloaded master
Here is output, and this work.
Also, if you made any changes in the file train.py, check that the indents are 4 spaces and not a tab character. Because the mixed version will not work
```
Z:\AI_SDK\VAE-GAN\voice_conversion-master_teeeeeeeeeest\voice_conversion-master\src>train.py --model_name my_train --dataset ../data/data_flickr --n_spkrs 2 --c
heckpoint_interval 5 --plot_interval 10  --n_epochs 10 --decay_epoch 5 --n_cpu 4 --batch_size 2
Namespace(b1=0.5, b2=0.999, batch_size=2, channels=1, checkpoint_interval=5, dataset='../data/data_flickr', decay_epoch=5, dim=32, epoch=0, img_height=128, img_
width=128, lr=0.0001, model_name='my_train', n_cpu=4, n_downsample=2, n_epochs=10, n_spkrs=2, plot_interval=10)
C:\Python38\lib\site-packages\torch\optim\adam.py:90: UserWarning: optimizer contains a parameter group with duplicate parameters; in future, this will cause an
 error; see github.com/pytorch/pytorch/issues/40967 for more information
  super(Adam, self).__init__(params, defaults)
[Epoch 1/10] [D loss: 3.329125] [G loss: 218.265294] :  50%|██████████████████████████████████▌                                  | 1/2 [00:29<00:23, 23.19s/it]
```

**Comment by magicse** [comment]
Try for test  5-6  secs duration  3 wav  files  for first speaker and 3 wav files  for second one.

**Comment by flancast90** [comment]
> Try for test 5-6 secs duration 3 wav files for first speaker and 3 wav files for second one. This is simple splitter of audio file to short fragments
> 
> ```
> from pydub import AudioSegment
> from pydub.silence import split_on_silence
> 
> # Load the audio file
> audio = AudioSegment.from_file("Z:/AI_SDK/VAE-GAN/test/mir.mp3", format="mp3")
> # resample
> audio = audio.set_frame_rate(16000)
> 
> # Split the audio file on silence, with a minimum silence length of 1000ms (1s) and a silence threshold of -50dB
> segments = split_on_silence(audio, min_silence_len=1000, silence_thresh=-40)
> 
> # Define the desired segment length in milliseconds (5s to 10s)
> segment_length = 5000  # 5 seconds
> max_segment_length = 10000  # 10 seconds
> 
> # Create a list to store the segments of desired length
> desired_segments = []
> 
> # Iterate through the segments
> for segment in segments:
>     # Get the segment duration
>     segment_duration = len(segment)
>     print (segment)
>     # If the segment is shorter than the desired length, skip it
>     if segment_duration < segment_length:
>         continue
>     
>     # If the segment is longer than the desired length, split it into multiple segments of desired length
>     if segment_duration > max_segment_length:
>         start = 0
>         while start < segment_duration:
>             end = min(start + segment_length, segment_duration)
>             desired_segments.append(segment[start:end])
>             start = end
>     else:
>         desired_segments.append(segment)
> 
> # Export the desired segments to separate audio files
> for i, segment in enumerate(desired_segments):
>     segment.export(f"Z:/AI_SDK/VAE-GAN/test/out/file_{i}.wav", format="wav")
> ```

I just downloaded the audio files from the website in the README, preprocessed them, and tried to train off of that, with the same issue.

I'm getting this interesting Numpy warning, which I think may be related to the error:
```
WARNING:py.warnings:C:\Users\Finn Lancaster\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\conv.py:137: UserWarning: Failed to initialize NumPy: module compiled against API version 0x10 but this version of numpy is 0xf . Check the section C-API incompatibility at the Troubleshooting ImportError section at https://numpy.org/devdocs/user/troubleshooting-importerror.html#c-api-incompatibility for indications on how to solve this problem . (Triggered internally at ..\torch\csrc\utils\tensor_numpy.cpp:84.)
  self.weight = Parameter(torch.empty(
```

If that is the case, it might be a dependency issue. I've installed the packages using the ``requirements.txt`` though, so I don't know how that would be the case. Would you mind sending the versions for all of the packages in the ``requirements.txt`` to compare?

**Comment by magicse** [comment]
librosa                      0.9.2
matplotlib                   3.5.2
matplotlib-inline            0.1.6
numpy                        1.23.3
scipy                        1.4.1
scikit-image                 0.19.2
soundfile                    0.11.0
torch                        1.12.1
torchaudio                   0.12.1
torchvision                  0.13.1
torchviz                     0.0.2
tqdm                         4.64.0
webrtcvad-wheels             2.0.11.post1

**Comment by magicse** [comment]
> WARNING:py.warnings:C:\Users\Finn Lancaster\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\conv.py:137: UserWarning: Failed to initialize NumPy: module compiled against API version 0x10 but this version of numpy is 0xf . Check the section C-API incompatibility at the Troubleshooting ImportError section at https://numpy.org/devdocs/user/troubleshooting-importerror.html#c-api-incompatibility for indications on how to solve this problem . (Triggered internally at ..\torch\csrc\utils\tensor_numpy.cpp:84.)
>   self.weight = Parameter(torch.empty(

is a compatibility issue between the NumPy version and the version of PyTorch

**Comment by magicse** [comment]
1 You don't need that big dataset. 
2 Voices in that dataset not good quality 
3 You could find any voiceover you want (for example from audio book) and split it with this simple script
[div_audio.zip](https://github.com/ebadawy/voice_conversion/files/11120248/div_audio.zip)

**Comment by flancast90** [comment]
> librosa                      0.9.2
> 
> matplotlib                   3.5.2
> 
> matplotlib-inline            0.1.6
> 
> numpy                        1.23.3
> 
> scipy                        1.4.1
> 
> scikit-image                 0.19.2
> 
> soundfile                    0.11.0
> 
> torch                        1.12.1 cpu
> 
> torchaudio                   0.12.1
> 
> torchvision                  0.13.1 cpu
> 
> torchviz                     0.0.2
> 
> tqdm                         4.64.0
> 
> webrtcvad-wheels             2.0.11.post1
> 
> 

Thanks! I'll try these. And what version of Python are you currently running? I've read that Python-latest doesn't always play nicely with numpy...

**Comment by flancast90** [comment]
> > WARNING:py.warnings:C:\Users\Finn Lancaster\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\conv.py:137: UserWarning: Failed to initialize NumPy: module compiled against API version 0x10 but this version of numpy is 0xf . Check the section C-API incompatibility at the Troubleshooting ImportError section at https://numpy.org/devdocs/user/troubleshooting-importerror.html#c-api-incompatibility for indications on how to solve this problem . (Triggered internally at ..\torch\csrc\utils\tensor_numpy.cpp:84.)
> 
> >   self.weight = Parameter(torch.empty(
> 
> 
> 
> is a compatibility issue between the NumPy version and the version of PyTorch
> 
> Try 
> 
> pip uninstall numpy
> 
> pip install numpy
> 
> or
> 
> pip install numpy --upgrade

These instructions will not work. Librosa requires a specific version of numpy. If you uninstall numpy and install the latest version with --upgrade, librosa will break. Currently I'm using the versions given in the requirements.txt for everything.

**Comment by flancast90** [comment]
> 1 You don't need that big dataset. 
> 
> 2 Voices in that dataset not good quality 
> 
> 3 You could find any voiceover you want (for example from audio book) and split it with this simple script
> 
> 3.1 Replace path in script for your path.
> 
> 4 Put splitted waves in folder project-> data -> data_flickr -> spkr_1 for speaker 1 and the same for spkr_2
> 
> 5 Run `preprocess.py --dataset "..\data\data_flickr" --test_size=0.25 --eval_size=0.25 --model_name my_train` or 
> 
> `preprocess.py --dataset "../data/data_flickr" --test_size=0.25 --eval_size=0.25 --model_name my_train`
> 
> [div_audio.zip](https://github.com/ebadawy/voice_conversion/files/11120426/div_audio.zip)
> 
> 

1. Yep, I happened to already have the dataset from some analysis I did years ago. For the training/processing, I'm only using 10000 files in each folder. 
2. The voices in the dataset are not great quality. The application I'm making is extremely niche, meaning that I'm having to make do with files with a lot of noise. 
3, 4, 5. These are unnecessary imo. Im trying to work with a certain voice, not just any voice online. It should still work, even if the files have a lot of noise, correct?

**Comment by flancast90** [comment]
> librosa 0.9.2 matplotlib 3.5.2 matplotlib-inline 0.1.6 numpy 1.23.3 scipy 1.4.1 scikit-image 0.19.2 soundfile 0.11.0 torch 1.12.1 cpu torchaudio 0.12.1 torchvision 0.13.1 cpu torchviz 0.0.2 tqdm 4.64.0 webrtcvad-wheels 2.0.11.post1

Found the issue. It seems that librosa is dependent on ``numba`` which requires a very specific version of ``numpy`` to work. TL;DR, I installed all of the versions you gave, and then did ``pip install --upgrade numba`` and think it's working ok now. I'll leave this issue open just in case I find any other issues.

**Comment by flancast90** [comment]
@magicse, I have updated the project's ``requirements.txt`` file to reflect the versions you sent, as well as the expected version of the ``numba`` dependency. See #27 for more details. Thank you for all the help!
